"""init

Revision ID: 0bb36d353fa9
Revises: 
Create Date: 2024-12-12 23:26:08.340858

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '0bb36d353fa9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
