"""add_m_t_m3

Revision ID: 61e855e57a5b
Revises: 8c380b15e38c
Create Date: 2024-12-25 11:33:45.428597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '61e855e57a5b'
down_revision: Union[str, None] = '8c380b15e38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpageassociations',
    sa.Column('kontrol_point_id', sa.String(), nullable=True),
    sa.Column('ages_category_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('unique_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['ages_category_id'], ['agecategorys.unique_id'] ),
    sa.ForeignKeyConstraint(['kontrol_point_id'], ['kontrolpoints.unique_id'] ),
    sa.PrimaryKeyConstraint('unique_id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpageassociations')
    # ### end Alembic commands ###
