"""add_uuid_str

Revision ID: 7d50e01c3ddd
Revises: aa6286dfcd33
Create Date: 2024-12-25 14:21:16.458229

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '7d50e01c3ddd'
down_revision: Union[str, None] = 'aa6286dfcd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
