"""initial7

Revision ID: aa6286dfcd33
Revises: 61e855e57a5b
Create Date: 2024-12-25 13:19:31.839529

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'aa6286dfcd33'
down_revision: Union[str, None] = '61e855e57a5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
